# System Exits
SUCCESS = 0
FAILED_TO_SAVE_FILE = 1

# Column definitions
COLUMN_NAME = 0
COLUMN_TIME_SEASON = 1
COLUMN_TIME_DAY = 2
COLUMN_FIRST_CHECK_IN = 3
COLUMN_FIRST_CHECK_OUT = 4

# Row definitions
ROW_HEADER = 0
ROW_FIRST_DATA = 1

# LibreOffice-Sheet max size definitions
MAX_CHECK_TIMESS = 30
MAX_COLUMNS = COLUMN_FIRST_CHECK_IN + MAX_CHECK_TIMESS * 2

MAX_NAME_ROWS = 100
HEADER_ROWS = 1
MAX_ROWS = MAX_NAME_ROWS + HEADER_ROWS